Repository sparsick/testcontainers-git, pull requests merged in 2024-01, with the labels that each got.

#57 feat: add support for rockstorm/git-server:2.43
  testcontainers-gitserver/src/main/java/com/github/sparsick/testcontainers/gitserver/GitServerVersions.java
  testcontainers-gitserver/src/test/java/com/github/sparsick/testcontainers/gitserver/plain/GitServerContainerTest.java
Labels: feature

#58 Adjust docs for 0.5.0
  README.md
  rewrite-testcontainers-gitserver/src/main/java/io/github/sparsick/testcontainers/gitserver/rewrite/recipe/RenamePackageOfGitHttpServerContainer.java
Labels: skip-changelog

#59 Update to Java 21
  .github/workflows/maven.yml
Labels: maintenance

#64 Update dependency snippets in README.md to version 0.5.0
  README.md
Labels: skip-changelog

#71 Fix file permission for pubKey Auth
  testcontainers-gitserver/src/main/java/com/github/sparsick/testcontainers/gitserver/plain/GitServerContainer.java
  testcontainers-gitserver/src/test/java/com/github/sparsick/testcontainers/gitserver/plain/GitServerContainerTest.java
Labels: bug
