Repository sparsick/testcontainers-git, pull requests merged in 2024-05, with the labels that each got.

#106 GitHttpServer broken by git/git-daemon Alpine update
  testcontainers-gitserver/src/main/java/com/github/sparsick/testcontainers/gitserver/http/GitHttpServerContainer.java
  testcontainers-gitserver/src/test/java/com/github/sparsick/testcontainers/gitserver/http/GitHttpServerContainerTest.java
Labels: bug

#107 Improve Wait Strategy
  testcontainers-gitserver/src/main/java/com/github/sparsick/testcontainers/gitserver/plain/GitServerContainer.java
Labels: bug

#115 fix: Use maven.compiler.release flags
  pom.xml
Labels: maintenance

#114 fix: Remove unnecessary dependency versions from pom
  testcontainers-gitserver/pom.xml
Labels: maintenance

#113 fix: Move sources and javadoc plugins to release profile
  pom.xml
Labels: maintenance

#118 feat: add support for rocktstorm 2.45
  README.md
  testcontainers-gitserver/src/main/java/com/github/sparsick/testcontainers/gitserver/GitServerVersions.java
  testcontainers-gitserver/src/test/java/com/github/sparsick/testcontainers/gitserver/plain/GitServerContainerTest.java
Labels: feature

#120 chore: harmonize nginx user and git user to root
  testcontainers-gitserver/src/main/java/com/github/sparsick/testcontainers/gitserver/http/GitHttpServerContainer.java
Labels: maintenance
